apiVersion : apps/v1
kind: Deployment
metadata:
  name: matheuandraderundevops 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matheuandraderundevops
  template:
    metadata:
      labels:
        app: matheuandraderundevops 
    spec:
      containers:
        - name: matheuandraderundevops 
          image: matheuandrade.azurecr.io/matheuandraderundevops
          ports:
          - containerPort: 80